### ISSUE TITLE
Memory leaks in SimModel when running Sensitivity Analysis

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite.SimModel#19]
Steps to reproduce:
* Run sensitivity for a standard PK-Sim Model in MoBi (Diclofenac for example)
* Select ALL parameters for the sensitivity (Advanced mode and select all parameters)
* Run sensitivity

* The memory usage gets very high, and much higher than just the amount of data saved by managed .NET
* The time to run simulations increases with time!! 

![image](https://user-images.githubusercontent.com/1041237/29979880-423f2170-8f15-11e7-9da0-00286c4268d5.png)

**Comment by msevestre** [comment]
As soon as the sensitivity is finsihed, the following occurs

* Memory goes down to 400 MB (e.g. memory leaks definitely in the calculation)
* results are ignored in MoBi. Something crashes silently and it looks like the sensitivity was not run

**Comment by Yuri05** [comment]
why do u think this is **SimModel**-Leak?

**Comment by msevestre** [comment]
@Yuri05 Because There is no .NET code in between..really

**Comment by Yuri05** [comment]
@msevestre Do you observe memory leaks also in population simulations? From SimModel's perspective it's the same use case.

**Comment by msevestre** [comment]
@Yuri05 I have only make this observation with Sensitivity but haven't checked for population.

**Comment by msevestre** [comment]
I have described all steps above however. Can't you reproduce it ?

**Comment by Yuri05** [comment]
> I have described all steps above however. Can't you reproduce it ?

It seems that there are memory leaks indeed. But not sure if the problem is in SimModel. 

E.g. in the project attached (where SA was already calculated, ca. 5650 simulations): [4.34_Opti.mbp3.zip](https://github.com/Open-Systems-Pharmacology/OSPSuite.SimModel/files/2625911/4.34_Opti.mbp3.zip)
1. Open project, Open SA, perform GC: memory usage ca. **348MB**
2. Run SA, perform GC: memory usage ca. **367MB**
3. Run SA again, perform GC: memory usage ca. **377MB**
4. Run SA again, perform GC: memory usage ca. **378MB**

Having SA already calculated, I would expected nearly the same usage in 1-4 (348MB)

I also do not observe SA becoming slower with every execution.

**Comment by msevestre** [comment]
64 bit might change the whole observations. I'd try to reproduce it with
7.3 if I were you

**Comment by Yuri05** [comment]
Cannot find any leakss in SimModel.
Also unable to reproduce the behaviour with Mobi 7.4.

Reopen if you can reproduce with 7.4 (in this case we should perform .NET profiling first)
